// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgTBRMLrVdDEVA5ybbPhI5VsRQ_XSmhqY',
    appId: '1:371879002618:web:92114a7bdfd107fd596443',
    messagingSenderId: '371879002618',
    projectId: 'test-97351',
    authDomain: 'test-97351.firebaseapp.com',
    storageBucket: 'test-97351.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwa6oNb6AYxx0VJZhDLQaXQ5-BbrCz7dY',
    appId: '1:371879002618:android:68245e160fb35ac0596443',
    messagingSenderId: '371879002618',
    projectId: 'test-97351',
    storageBucket: 'test-97351.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmbLfarflpyW6e7Om0-LcS0aeetuz3rnk',
    appId: '1:371879002618:ios:ddab14a26d1d5bf0596443',
    messagingSenderId: '371879002618',
    projectId: 'test-97351',
    storageBucket: 'test-97351.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmbLfarflpyW6e7Om0-LcS0aeetuz3rnk',
    appId: '1:371879002618:ios:ac2f5d3cbcddd134596443',
    messagingSenderId: '371879002618',
    projectId: 'test-97351',
    storageBucket: 'test-97351.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
